Repository softeerbootcamp-2nd/A1-PoongCha, pull requests merged in 2023-08, with the labels that each got.

#30 FE/0805/사전설문_추가질문 선택지 그룹1-4
  front/src/Components/Common/RadioBtn/index.jsx
  front/src/Components/Survey/SurveyOption/index.jsx
  front/src/Components/Survey/SurveyOptionGroup/index.jsx
  front/src/Pages/SurveyPage/AgeSurvey/index.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/index.jsx
  front/src/styles/theme.js
Labels: ✨ Feature

#35 FE/0806/추천제안 사전 질문 UI
  front/src/Components/Survey/LifestylePersona/index.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/index.jsx
Labels: ✨ Feature

#37 feat : 라이프 스타일 엿보기 UI
  front/src/App.jsx
  front/src/Components/Survey/LifestylePersona/index.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/index.jsx
  front/src/hooks/useOnClickPopUp.jsx
Labels: 🎨 Html&css

#38 FE/0805/사전설문_추가질문 최대 예산 슬라이더
  front/src/Components/Survey/SurveyHeader/index.jsx
  front/src/Components/Survey/SurveyOption/index.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/BudgetSliderGroup.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/index.jsx
  front/src/styles/theme.js
Labels: ✨ Feature

#39 FE/0806/사전설문_추가질문 완료 버튼
  front/src/Components/Common/Button/Button.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/index.jsx
  front/src/Pages/SurveyPage/index.jsx
Labels: ✨ Feature

#40 FE/0806/추가질문_추천완료 질문답변요약
  front/src/Pages/EtcPage/QNASummary/index.jsx
  front/src/Pages/EtcPage/index.jsx
  front/src/Pages/EtcPage/test.txt
  front/src/Pages/SurveyPage/ExtraSurvey/BudgetSliderGroup.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/index.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/surveyData.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/PopUp/Cover/index.jsx
  front/src/Pages/SurveyPage/index.jsx
  front/src/assets/images/etc-end-palisade.svg
  front/src/styles/theme.js
Labels: ✨ Feature

#44 FE/0807/사전설문_라이프스타일 설문 페이지 오류 수정, 데이터 추가
  front/src/Components/Survey/LifestylePersona/index.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/index.jsx
  front/src/Pages/SurveyPage/styles/index.jsx
  front/src/styles/theme.js
Labels: 🎨 Html&css, 🐞 BugFix

#45 Fe/feature/31 라이프스타일상세설명컴포넌트개발
  front/src/Pages/SurveyPage/LifestyleSurvey/PopUp/Detail/index.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/PopUp/index.jsx
  front/src/assets/extraoption/fca-2-s-jpg.svg
  front/src/assets/extraoption/roa-s-jpg.svg
  front/src/assets/trimsideimg/trimSideNavy.svg
  front/src/styles/theme.js
Labels: ✨ Feature

#49 Fe/feature/46 추천완료카드
  front/src/Pages/EndPage/Card/index.jsx
  front/src/Pages/EndPage/index.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/index.jsx
  front/src/assets/car.svg
  front/src/assets/icons/hyundaicardlogo.svg
  front/src/assets/point.svg
Labels: ✨ Feature

#48 FE/0807/추천제안, 추가질문_추천완료 페이지 추천차량 요약 정보 표시
  front/src/Components/Common/SelectedItem/SelectedItem.jsx
  front/src/Components/Common/Summary/SelectedItem/SelectedItem.jsx
  front/src/Components/Common/Summary/index.jsx
  front/src/Pages/EndPage/Card/index.jsx
  front/src/Pages/EndPage/index.jsx
  front/src/Pages/EtcPage/index.jsx
  front/src/styles/theme.js
  readme.md
Labels: ✨ Feature, 🎨 Html&css

#52 FE/0807/추천제안_마무리작업1
  front/.vite/deps_temp_f0ef32fe/package.json
  front/src/App.jsx
  front/src/Components/Common/RadioBtn/index.jsx
  front/src/Components/Survey/SurveyHeader/index.jsx
  front/src/Components/Survey/SurveyOption/index.jsx
  front/src/Components/Survey/SurveyOptionGroup/index.jsx
  front/src/Pages/SurveyPage/AgeSurvey/index.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/BudgetSliderGroup.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/index.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/index.reducer.js
  front/src/Pages/SurveyPage/LifestyleSurvey/index.jsx
  front/src/utils/ScrollToTop.jsx
  front/src/utils/constants.jsx
Labels: ✨ Feature, 🔨 Refactor

#55 FE/0808/라우터 리팩토링
  front/.vite/deps_temp_eeaf6a54/package.json
  front/src/Components/Survey/ProgressBar/index.jsx
  front/src/Pages/EtcPage/QNASummary/index.jsx
  front/src/Pages/LandingPage/index.jsx
  front/src/Pages/SurveyPage/AgeSurvey/index.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/index.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/index.jsx
  front/src/Pages/SurveyPage/index.jsx
  front/src/hooks/useButtonNavigation.jsx
  front/src/main.jsx
  front/src/styles/global-style.js
Labels: 🔨 Refactor

#74 FE/0809/트림선택-색상 선택 버튼과 레이아웃 수정
  front/.vite/deps_temp_2e810e58/package.json
  front/src/Components/Custom/ModelItemOption/index.jsx
  front/src/Components/Custom/ModelItemOptionGroup/index.jsx
  front/src/Components/Custom/TrimOption/index.jsx
  front/src/Components/Custom/TrimOptionGroup/index.jsx
  front/src/Components/Header/OptionalHeader/Navigation/index.jsx
  front/src/Components/Header/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomBar/index.jsx
  front/src/Pages/CustomPage/TrimPage/index.jsx
Labels: ✨ Feature, 🎨 Html&css

#77 FE/0809/트림선택-툴팁
  front/src/Components/Custom/ModelItemOptionGroup/index.jsx
  front/src/Components/Custom/Tooltip/index.jsx
  front/src/Components/Custom/TrimOptionGroup/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/index.reducer.js
  front/src/Pages/CustomPage/TrimPage/index.jsx
  front/src/assets/icons/tooltip-lightbulb.svg
  front/src/assets/icons/tooltip-tail.svg
  front/src/hooks/useTooltip.jsx
  front/src/styles/theme.js
Labels: ✨ Feature

#78 FE/0809/트림 선택 페이지 레이아웃 수정
  front/src/Components/Custom/TrimOptionGroup/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/index.jsx
  front/src/Pages/CustomPage/TrimPage/index.jsx
Labels: 🎨 Html&css

#79 FE/0809/트림선택-기본 옵션 팝업
  front/src/Components/Custom/DefaultOption/index.jsx
  front/src/Components/Custom/DefaultOptionPopup/index.jsx
  front/src/Components/Custom/TrimOption/index.jsx
  front/src/Components/Header/OptionalHeader/Navigation/index.jsx
  front/src/assets/icons/close.svg
  front/src/assets/images/default-option-popup-sample.svg
  front/src/hooks/useOnClickPopUp.jsx
Labels: ✨ Feature

#82 FE/0810/트림선택-트림 비교하기 팝업
  .DS_Store
  front/.vite/deps_temp_7489894e/package.json
  front/src/Components/Common/BackgroundOverlay/index.jsx
  front/src/Components/Custom/TrimOptionGroup/index.jsx
  front/src/Components/Survey/LifestylePersona/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimComparisonPopup/index.jsx
  front/src/Pages/CustomPage/TrimPage/index.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/PopUp/index.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/index.jsx
  front/src/assets/images/trim-comparison-popup-sample.png
Labels: ✨ Feature

#83 FE/0810/트림선택-고르기 어렵다면? 팝업 (네비게이션)
  .DS_Store
  front/.vite/deps_temp_ccd5331b/package.json
  front/src/Components/Common/OverlaidPopup/BackgroundOverlay.jsx
  front/src/Components/Common/OverlaidPopup/index.jsx
  front/src/Components/Custom/TrimOptionGroup/TrimOption.jsx
  front/src/Components/Custom/TrimOptionGroup/index.jsx
  front/src/Components/Header/index.jsx
  front/src/Pages/CustomPage/TrimPage/ModelItemsDescriptionPopup/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimComparisonPopup/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/index.jsx
  front/src/Pages/CustomPage/TrimPage/index.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/index.jsx
  front/src/assets/icons/help-circle.svg
  front/src/assets/images/model-item-popup-sample1.png
  front/src/assets/images/model-item-popup-sample2.png
Labels: ✨ Feature

#87 FE/0810/트림선택-트림 변경 팝업
  front/src/Components/Common/ImgItem/ImgItem.jsx
  front/src/Components/Common/RadioBtn/Radio.jsx
  front/src/Components/Common/RadioBtn/RadioGroup.jsx
  front/src/Components/Common/RadioBtn/index.jsx
  front/src/Components/Custom/TrimOptionGroup/TrimOption.jsx
  front/src/Components/Survey/SurveyOption/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimChangePopup/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/mockData.js
Labels: ✨ Feature

#90 FE/0810/색상선택-색상 옵션 컴포넌트, 라디오 기능
  front/src/Components/CommonSurvey/OptionGroup.jsx
  front/src/Components/CommonSurvey/index.jsx
  front/src/Components/Custom/ColorOptionGroup/ColorOption.jsx
  front/src/Components/Custom/ColorOptionGroup/index.jsx
  front/src/Components/Custom/ModelItemOptionGroup/ModelItemOption.jsx
  front/src/Components/Custom/ModelItemOptionGroup/index.jsx
  front/src/Components/Custom/TrimOptionGroup/DefaultOption.jsx
  front/src/Components/Custom/TrimOptionGroup/TrimOption.jsx
  front/src/Components/Custom/TrimOptionGroup/index.jsx
  front/src/Components/Survey/LifestylePersona/index.jsx
  front/src/Components/Survey/SurveyOption/index.jsx
  front/src/Components/Survey/SurveyOptionGroup/index.jsx
  front/src/Pages/CustomPage/ColorPage/ColorChangePopup/index.jsx
  front/src/Pages/CustomPage/ColorPage/ColorCustomSIdeBar/index.jsx
  front/src/Pages/CustomPage/ColorPage/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/index.jsx
  front/src/Pages/SurveyPage/AgeSurvey/index.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/index.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/index.jsx
  front/src/assets/checkcircle/check-24-white.svg
  front/src/assets/icons/24-chevron-down.svg
  front/src/assets/icons/24-chevron-up.svg
  front/src/styles/theme.js
Labels: ✨ Feature

#102 #101 setting : be/setting/101-멀티-모듈-세팅
  backend/boot-loader/build.gradle
  backend/boot-loader/gradle/wrapper/gradle-wrapper.jar
  backend/boot-loader/gradle/wrapper/gradle-wrapper.properties
  backend/boot-loader/gradlew
  backend/boot-loader/gradlew.bat
  backend/boot-loader/src/main/java/com/poongcha/bootloader/BootLoaderApplication.java
  backend/boot-loader/src/main/resources/application.properties
  backend/boot-loader/src/test/java/com/poongcha/bootloader/BootLoaderApplicationTests.java
  backend/car/build.gradle
  backend/car/gradle/wrapper/gradle-wrapper.jar
  backend/car/gradle/wrapper/gradle-wrapper.properties
  backend/car/gradlew
  backend/car/gradlew.bat
  backend/car/src/main/java/com/poongcha/car/CarApplication.java
  backend/car/src/main/resources/application.properties
  backend/car/src/test/java/com/poongcha/car/CarApplicationTests.java
  backend/recommend/build.gradle
  backend/recommend/gradle/wrapper/gradle-wrapper.jar
  backend/recommend/gradle/wrapper/gradle-wrapper.properties
  backend/recommend/gradlew
  backend/recommend/gradlew.bat
  backend/recommend/src/main/java/com/poongcha/recommend/RecommendApplication.java
  backend/recommend/src/main/resources/application.properties
  backend/recommend/src/test/java/com/poongcha/recommend/RecommendApplicationTests.java
  backend/settings.gradle
Labels: ⚙ Setting

#108 Be/setting/103 datasource 설정
  backend/boot-loader/src/main/java/com/poongcha/bootloader/BootLoaderApplication.java
  backend/boot-loader/src/main/resources/application.properties
  backend/boot-loader/src/main/resources/application.yml
  backend/build.gradle
  backend/car/src/main/java/com/poongcha/car/config/CarDataJdbcConfig.java
  backend/car/src/main/java/com/poongcha/car/config/CarDataSourceConfig.java
  backend/car/src/main/java/com/poongcha/car/config/CarJdbcConfig.java
  backend/car/src/main/java/com/poongcha/car/config/CarTransactionConfig.java
  backend/car/src/main/resources/application-car.yml
  backend/car/src/main/resources/application.properties
  backend/recommend/src/main/java/com/poongcha/recommend/config/RecommendDataJdbcConfig.java
  backend/recommend/src/main/java/com/poongcha/recommend/config/RecommendDataSourceConfig.java
  backend/recommend/src/main/java/com/poongcha/recommend/config/RecommendJdbcConfig.java
  backend/recommend/src/main/java/com/poongcha/recommend/config/RecommendTransactionConfig.java
  backend/recommend/src/main/resources/application-recommend.yml
  backend/recommend/src/main/resources/application.properties
Labels: ⚙ Setting

#107 FE/96/옵션선택 태크 컨테이너
  front/src/Components/Custom/OptionItem/index.jsx
  front/src/Components/Custom/OptionTag/index.jsx
  front/src/Pages/CustomPage/OptionPage/AdditionalOption/index.jsx
  front/src/Pages/CustomPage/OptionPage/DefaultOption/index.jsx
  front/src/Pages/CustomPage/OptionPage/index.jsx
  front/src/Pages/CustomPage/OptionPage/optionData.js
  front/src/Pages/CustomPage/OptionPage/tagIcon.js
  front/src/assets/checkcircle/check-16-blue.svg
  front/src/assets/checkcircle/check-16-grey.svg
  front/src/assets/icons/chevron-left.svg
  front/src/assets/icons/chevron-right.svg
  front/src/assets/optionTag/Select/all.svg
  front/src/assets/optionTag/Select/convenience.svg
  front/src/assets/optionTag/Select/main.svg
  front/src/assets/optionTag/Select/parking.svg
  front/src/assets/optionTag/Select/performance.svg
  front/src/assets/optionTag/Select/safety.svg
  front/src/assets/optionTag/Select/style.svg
  front/src/assets/optionTag/Select/temperature.svg
  front/src/assets/optionTag/notSelect/all.svg
  front/src/assets/optionTag/notSelect/convenience.svg
  front/src/assets/optionTag/notSelect/main.svg
  front/src/assets/optionTag/notSelect/parking.svg
  front/src/assets/optionTag/notSelect/performance.svg
  front/src/assets/optionTag/notSelect/safety.svg
  front/src/assets/optionTag/notSelect/style.svg
  front/src/assets/optionTag/notSelect/temperature.svg
Labels: ✨ Feature

#116 Fe/0813/결과페이지 UI 완성
  front/src/Components/Common/Summary/SelectedItem/SelectedItem.jsx
  front/src/Components/Header/index.jsx
  front/src/Components/Result/Accordian/index.jsx
  front/src/Pages/ResultPage/Card/index.jsx
  front/src/Pages/ResultPage/index.jsx
  front/src/assets/icons/download.svg
  front/src/assets/image342.svg
Labels: ✨ Feature, 🎨 Html&css

#106 FE/0812/옵션 팝업
  .DS_Store
  front/src/Components/Custom/OptionItem/index.jsx
  front/src/Pages/CustomPage/OptionPage/AdditionalOption/index.jsx
  front/src/Pages/CustomPage/OptionPage/DefaultOption/index.jsx
  front/src/Pages/CustomPage/OptionPage/OptionPopup/Card.jsx
  front/src/Pages/CustomPage/OptionPage/OptionPopup/index.jsx
  front/src/Pages/CustomPage/OptionPage/TaggedPage/OptionTooltip.jsx
  front/src/Pages/CustomPage/OptionPage/TaggedPage/index.jsx
  front/src/assets/icons/arrow-left-32-white.svg
  front/src/assets/icons/arrow-right-32-white.svg
  front/src/assets/icons/arrow-right.svg
  front/src/assets/icons/option-tooltip-tail.svg
  front/src/assets/icons/plus.svg
  front/src/assets/images/option-popup-sample.svg
  front/src/assets/images/tagged-page-sample.svg
  front/src/hooks/useOnClickPopUp.jsx
Labels: ✨ Feature

#121 refactor: 옵션페이지 중복 컴포넌트 제거
  front/src/Components/Custom/OptionTag/index.jsx
  front/src/Pages/CustomPage/OptionPage/AdditionalOption/index.jsx
  front/src/Pages/CustomPage/OptionPage/AllOptions/index.jsx
  front/src/Pages/CustomPage/OptionPage/index.jsx
  front/src/Pages/CustomPage/OptionPage/optionData.js
Labels: 🔨 Refactor

#120 Be/feat/118 차량 조회 api
  backend/car/src/main/java/com/poongcha/car/application/CarTypeQueryService.java
  backend/car/src/main/java/com/poongcha/car/application/dto/CarTypeDefaultResponse.java
  backend/car/src/main/java/com/poongcha/car/application/mapper/CarTypeMapper.java
  backend/car/src/main/java/com/poongcha/car/domain/CarType.java
  backend/car/src/main/java/com/poongcha/car/domain/CarTypeRepository.java
  backend/car/src/main/java/com/poongcha/car/presentation/CarTypeController.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarTypeAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarTypeSteps.java
Labels: 📃 Docs, 📬 API, ✅ Test

#125 Be/feat/123 트림 기능 구현
  backend/car/src/main/java/com/poongcha/car/application/TrimCommandService.java
  backend/car/src/main/java/com/poongcha/car/application/TrimQueryService.java
  backend/car/src/main/java/com/poongcha/car/application/dto/TrimCreateRequest.java
  backend/car/src/main/java/com/poongcha/car/application/dto/TrimDefaultResponse.java
  backend/car/src/main/java/com/poongcha/car/application/mapper/TrimMapper.java
  backend/car/src/main/java/com/poongcha/car/domain/MinPrice.java
  backend/car/src/main/java/com/poongcha/car/domain/Trim.java
  backend/car/src/main/java/com/poongcha/car/domain/TrimName.java
  backend/car/src/main/java/com/poongcha/car/domain/TrimRepository.java
  backend/car/src/main/java/com/poongcha/car/exception/HttpNotFoundException.java
  backend/car/src/main/java/com/poongcha/car/presentation/DefaultExceptionControllerAdvice.java
  backend/car/src/main/java/com/poongcha/car/presentation/TrimController.java
  backend/car/src/test/java/com/poongcha/car/acceptance/TrimAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/TrimSteps.java
  backend/car/src/test/java/com/poongcha/car/util/DataInitializeExecutionListener.java
Labels: ✨ Feature, 📃 Docs, 📬 API, ✅ Test

#131 Be/feat/126 차량 색상 기능 구현
  backend/car/src/main/java/com/poongcha/car/application/CarColorCommandService.java
  backend/car/src/main/java/com/poongcha/car/application/TrimCommandService.java
  backend/car/src/main/java/com/poongcha/car/application/TrimQueryService.java
  backend/car/src/main/java/com/poongcha/car/application/dto/CarColorCreateRequest.java
  backend/car/src/main/java/com/poongcha/car/application/dto/CarColorDefaultResponse.java
  backend/car/src/main/java/com/poongcha/car/application/dto/TrimAddCarColorRequest.java
  backend/car/src/main/java/com/poongcha/car/application/dto/TrimCarColorResponse.java
  backend/car/src/main/java/com/poongcha/car/application/mapper/CarColorMapper.java
  backend/car/src/main/java/com/poongcha/car/domain/CarColor.java
  backend/car/src/main/java/com/poongcha/car/domain/CarColorName.java
  backend/car/src/main/java/com/poongcha/car/domain/CarColorRepository.java
  backend/car/src/main/java/com/poongcha/car/domain/CarColorType.java
  backend/car/src/main/java/com/poongcha/car/domain/Trim.java
  backend/car/src/main/java/com/poongcha/car/domain/TrimCarColor.java
  backend/car/src/main/java/com/poongcha/car/domain/TrimRepository.java
  backend/car/src/main/java/com/poongcha/car/exception/BadRequestException.java
  backend/car/src/main/java/com/poongcha/car/presentation/CarColorController.java
  backend/car/src/main/java/com/poongcha/car/presentation/CarTypeController.java
  backend/car/src/main/java/com/poongcha/car/presentation/TrimController.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarColorAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarColorSteps.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarTypeSteps.java
  backend/car/src/test/java/com/poongcha/car/acceptance/TrimAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/TrimSteps.java
  backend/car/src/test/java/com/poongcha/car/util/DataInitializeExecutionListener.java
Labels: ✨ Feature, 📃 Docs, 📬 API, ✅ Test

#134 feat: fetch함수, 에러처리 개발
  front/src/utils/error.js
  front/src/utils/fetch.js
Labels: ✨ Feature

#139 Be/feat/135 차량 색상 정책 구현
  backend/car/src/main/java/com/poongcha/car/application/CarColorCommandService.java
  backend/car/src/main/java/com/poongcha/car/application/dto/CarColorAddIncompatibleColorRequest.java
  backend/car/src/main/java/com/poongcha/car/application/dto/CarColorDefaultResponse.java
  backend/car/src/main/java/com/poongcha/car/application/dto/CarTypeDefaultResponse.java
  backend/car/src/main/java/com/poongcha/car/application/mapper/CarColorMapper.java
  backend/car/src/main/java/com/poongcha/car/domain/CarColor.java
  backend/car/src/main/java/com/poongcha/car/domain/CarColorRepository.java
  backend/car/src/main/java/com/poongcha/car/domain/IncompatibleCarColor.java
  backend/car/src/main/java/com/poongcha/car/presentation/CarColorController.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarColorAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarColorSteps.java
  backend/car/src/test/java/com/poongcha/car/acceptance/TrimAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/TrimSteps.java
  backend/car/src/test/java/com/poongcha/car/util/DataInitializeExecutionListener.java
Labels: ✨ Feature, 📃 Docs, 📬 API, ✅ Test

#143 Be/feat/142 차량 색상별 이미지
  backend/car/src/main/java/com/poongcha/car/application/TrimCommandService.java
  backend/car/src/main/java/com/poongcha/car/application/TrimQueryService.java
  backend/car/src/main/java/com/poongcha/car/application/dto/CarColorDefaultResponse.java
  backend/car/src/main/java/com/poongcha/car/application/dto/TrimAddCarColorRequest.java
  backend/car/src/main/java/com/poongcha/car/application/mapper/CarColorMapper.java
  backend/car/src/main/java/com/poongcha/car/domain/Trim.java
  backend/car/src/main/java/com/poongcha/car/domain/TrimCarColor.java
  backend/car/src/main/java/com/poongcha/car/domain/TrimExteriorImageUrl.java
  backend/car/src/main/java/com/poongcha/car/domain/TrimInteriorImageUrl.java
  backend/car/src/main/java/com/poongcha/car/domain/TrimRotationImageBaseUrl.java
  backend/car/src/test/java/com/poongcha/car/acceptance/TrimAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/TrimSteps.java
Labels: ✨ Feature, 📃 Docs, 📬 API, ✅ Test

#141 FE/0816/옵션 선택 페이지 수정, 애니메이션 추가
  front/src/Components/Custom/ModelItemOptionGroup/index.jsx
  front/src/Components/Custom/OptionItem/index.jsx
  front/src/Components/Custom/OptionTag/index.jsx
  front/src/Components/Header/OptionalHeader/ProgressBar.jsx
  front/src/Components/Survey/ProgressBar/index.jsx
  front/src/Pages/CustomPage/ColorPage/ColorChangePopup/index.jsx
  front/src/Pages/CustomPage/OptionPage/AllOptions/TaggedPage/OptionModal.jsx
  front/src/Pages/CustomPage/OptionPage/AllOptions/TaggedPage/index.jsx
  front/src/Pages/CustomPage/OptionPage/AllOptions/index.jsx
  front/src/Pages/CustomPage/OptionPage/OptionPopup/Card.jsx
  front/src/Pages/CustomPage/OptionPage/OptionPopup/index.jsx
  front/src/Pages/CustomPage/OptionPage/index.jsx
  front/src/Pages/CustomPage/OptionPage/optionData.js
  front/src/Pages/CustomPage/TrimPage/TrimComparisonPopup/index.jsx
  front/src/Pages/EndPage/Card/index.jsx
  front/src/Pages/EtcPage/QNASummary/index.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/index.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/index.jsx
  front/src/styles/global-style.js
Labels: 🐞 BugFix, 🔨 Refactor

#145 Be/feat/129 차량 컴포넌트 기능 구현
  backend/car/src/main/java/com/poongcha/car/application/CarComponentCommandService.java
  backend/car/src/main/java/com/poongcha/car/application/CarComponentGroupCommandService.java
  backend/car/src/main/java/com/poongcha/car/application/CarComponentGroupMapper.java
  backend/car/src/main/java/com/poongcha/car/application/CarComponentMapper.java
  backend/car/src/main/java/com/poongcha/car/application/CarTypeCommandService.java
  backend/car/src/main/java/com/poongcha/car/application/CarTypeQueryService.java
  backend/car/src/main/java/com/poongcha/car/application/dto/CarComponentCreateRequest.java
  backend/car/src/main/java/com/poongcha/car/application/dto/CarComponentGroupAddCarComponentRequest.java
  backend/car/src/main/java/com/poongcha/car/application/dto/CarComponentGroupCreateRequest.java
  backend/car/src/main/java/com/poongcha/car/application/dto/CarComponentGroupResponse.java
  backend/car/src/main/java/com/poongcha/car/application/dto/CarComponentResponse.java
  backend/car/src/main/java/com/poongcha/car/application/dto/CarTypeAddCarComponentGroupRequest.java
  backend/car/src/main/java/com/poongcha/car/domain/AdditionalPrice.java
  backend/car/src/main/java/com/poongcha/car/domain/CarComponent.java
  backend/car/src/main/java/com/poongcha/car/domain/CarComponentGroup.java
  backend/car/src/main/java/com/poongcha/car/domain/CarComponentGroupCarComponent.java
  backend/car/src/main/java/com/poongcha/car/domain/CarComponentGroupName.java
  backend/car/src/main/java/com/poongcha/car/domain/CarComponentGroupRepository.java
  backend/car/src/main/java/com/poongcha/car/domain/CarComponentName.java
  backend/car/src/main/java/com/poongcha/car/domain/CarComponentRepository.java
  backend/car/src/main/java/com/poongcha/car/domain/CarType.java
  backend/car/src/main/java/com/poongcha/car/domain/CarTypeCarComponentGroup.java
  backend/car/src/main/java/com/poongcha/car/domain/DescriptionImageUrl.java
  backend/car/src/main/java/com/poongcha/car/domain/SelectionHelpTooltip.java
  backend/car/src/main/java/com/poongcha/car/presentation/CarComponentController.java
  backend/car/src/main/java/com/poongcha/car/presentation/CarComponentGroupController.java
  backend/car/src/main/java/com/poongcha/car/presentation/CarTypeController.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarComponentAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarComponentSteps.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarTypeAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarTypeSteps.java
  backend/car/src/test/java/com/poongcha/car/util/DataInitializeExecutionListener.java
Labels: ✨ Feature, 📃 Docs, 📬 API, ✅ Test

#150 FE/0818/Survey 컴포넌트 재사용하기
  front/src/Components/Common/Radio/index.jsx
  front/src/Components/Common/RadioGroup/index.jsx
  front/src/Components/Custom/ModelItemOptionGroup/index.jsx
  front/src/Components/Custom/ModelItemOptionLabel/index.jsx
  front/src/Components/Custom/Tooltip/index.jsx
  front/src/Components/Custom/TrimOptionGroup/index.jsx
  front/src/Components/Custom/TrimOptionLabel/DefaultOption.jsx
  front/src/Components/Custom/TrimOptionLabel/index.jsx
  front/src/Components/Survey/AgeQuestionLabel/index.jsx
  front/src/Components/Survey/ExtraQuestionLabel/index.jsx
  front/src/Components/Survey/LifestyleQuestionLabel/index.jsx
  front/src/Components/Survey/PageIndicator/index.jsx
  front/src/Components/Survey/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/index.jsx
  front/src/Pages/SurveyPage/AgeSurvey/index.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/index.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/PopUp/Detail/index.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/PopUp/index.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/index.jsx
  front/src/hooks/useRadio.jsx
Labels: 🔨 Refactor

#154 FE/0816/세부선택 색상 API적용 완료
  front/package.json
  front/src/Components/Custom/CarView/CarRotateViewer/index.jsx
  front/src/Components/Custom/CarView/index.jsx
  front/src/Components/Custom/ColorOptionGroup/ColorOption.jsx
  front/src/Components/Custom/ColorOptionGroup/index.jsx
  front/src/Pages/CustomPage/ColorPage/ColorCustomSIdeBar/index.jsx
  front/src/Pages/CustomPage/ColorPage/index.jsx
  front/src/Pages/CustomPage/ColorPage/mockColorData.js
Labels: ✨ Feature, 📬 API

#153 FE/0819/옵션 선택 페이지 고치는 중
  .DS_Store
  front/public/image/extraoption/option1_1.svg
  front/public/image/extraoption/option1_2.svg
  front/public/image/extraoption/option1_3.svg
  front/public/image/extraoption/option1_4.svg
  front/public/image/extraoption/option1_5.svg
  front/public/image/extraoption/option1_6.svg
  front/public/image/extraoption/option2_1.svg
  front/public/image/extraoption/option3_1.svg
  front/public/image/extraoption/option4_1.svg
  front/public/image/extraoption/option5_1.svg
  front/public/image/extraoption/option6_1.svg
  front/public/image/extraoption/option7_1.svg
  front/public/image/extraoption/option8_1.svg
  front/src/Components/Common/RadioGroup/index.jsx
  front/src/Components/Custom/OptionItem/index.jsx
  front/src/Components/Custom/OptionTag/index.jsx
  front/src/Components/Custom/OptionTagLabel/index.jsx
  front/src/Components/Header/index.jsx
  front/src/Components/Survey/Title/index.jsx
  front/src/Pages/CustomPage/OptionPage/AllOptions/index.jsx
  front/src/Pages/CustomPage/OptionPage/OptionCatalogue/DefaultView/index.jsx
  front/src/Pages/CustomPage/OptionPage/OptionCatalogue/SituationView/OptionTooltip.jsx
  front/src/Pages/CustomPage/OptionPage/OptionCatalogue/SituationView/index.jsx
  front/src/Pages/CustomPage/OptionPage/OptionCatalogue/index.jsx
  front/src/Pages/CustomPage/OptionPage/OptionPopup/Card.jsx
  front/src/Pages/CustomPage/OptionPage/OptionPopup/index.jsx
  front/src/Pages/CustomPage/OptionPage/index.jsx
  front/src/Pages/CustomPage/OptionPage/optionData.js
  front/src/Pages/CustomPage/OptionPage/tagData.js
  front/src/Pages/CustomPage/OptionPage/tagIcon.js
  front/src/assets/images/optionItem_sample.svg
  front/src/hooks/useRadio.jsx
  front/src/utils/constants.jsx
Labels: 🔨 Refactor

#161 BE/setting/158-테스트 모듈 분리
  backend/car/build.gradle
  backend/car/src/test/java/com/poongcha/car/acceptance/CarColorAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarColorSteps.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarComponentAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarComponentSteps.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarEstimateAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarOptionAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarOptionBrandAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarOptionBrandSteps.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarOptionGroupAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarOptionGroupSteps.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarOptionGroupTooltipAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarOptionGroupTooltipSteps.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarOptionSteps.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarOptionTagAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarOptionTagSteps.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarTypeAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarTypeSteps.java
  backend/car/src/test/java/com/poongcha/car/acceptance/TrimAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/TrimSteps.java
  backend/car/src/test/java/com/poongcha/car/util/CarAcceptanceTest.java
  backend/common-test/build.gradle
  backend/common-test/gradle/wrapper/gradle-wrapper.properties
  backend/common-test/gradlew
  backend/common-test/gradlew.bat
  backend/common-test/src/main/java/com/poongcha/commontest/CommonTestApplication.java
  backend/common-test/src/main/resources/application.properties
  backend/common-test/src/testFixtures/java/util/AcceptanceTest.java
  backend/common-test/src/testFixtures/java/util/DocumentationTest.java
  backend/settings.gradle
Labels: ⚙ Setting

#160 Fe/setting/156 frontend cicd 구축
  .github/workflows/frontend-ci.yml
  .github/workflows/frontend-cicd.yml
Labels: 🌏 Deploy, ⚙ Setting

#159 FE/0820/TooltipProvider, PopupProvider
  front/.vite/deps_temp_d5bb3114/package.json
  front/src/Components/Common/PopupProvider/OverlaidPopup/BackgroundOverlay.jsx
  front/src/Components/Common/PopupProvider/OverlaidPopup/index.jsx
  front/src/Components/Common/PopupProvider/index.jsx
  front/src/Components/Common/RadioGroup/index.jsx
  front/src/Components/Common/TooltipProvider/index.jsx
  front/src/Components/Custom/CarView/index.jsx
  front/src/Components/Custom/ColorOptionGroup/index.jsx
  front/src/Components/Custom/ModelItemOptionLabel/index.jsx
  front/src/Components/Custom/OptionItem/index.jsx
  front/src/Components/Custom/OptionTagLabel/index.jsx
  front/src/Components/Custom/Tooltip/index.jsx
  front/src/Components/Custom/TrimOptionLabel/index.jsx
  front/src/Components/Survey/AgeQuestionLabel/index.jsx
  front/src/Components/Survey/ExtraQuestionLabel/index.jsx
  front/src/Components/Survey/LifestyleQuestionLabel/index.jsx
  front/src/Pages/CustomPage/OptionPage/OptionCatalogue/SituationView/OptionTooltip.jsx
  front/src/Pages/CustomPage/OptionPage/OptionCatalogue/SituationView/index.jsx
  front/src/Pages/CustomPage/OptionPage/index.jsx
  front/src/Pages/CustomPage/TrimPage/BackToSurveyPopup/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/mockData.js
  front/src/Pages/CustomPage/TrimPage/index.jsx
  front/src/Pages/SurveyPage/AgeSurvey/index.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/index.jsx
  front/src/Pages/SurveyPage/LifestyleSurvey/index.jsx
  front/src/hooks/useOnClickPopUp.jsx
  front/src/hooks/useTooltip.jsx
Labels: 🔨 Refactor

#170 FE/0821/엔진, 바디, 구동방식 api 연결
  front/src/Components/Custom/ModelItemOptionLabel/index.jsx
  front/src/Pages/CustomPage/OptionPage/OptionCatalogue/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/index.reducer.js
Labels: 📬 API

#175 FE/0821/상세보기,결과페이지 context적용
  front/src/App.jsx
  front/src/Components/Custom/CarView/index.jsx
  front/src/Components/Header/OptionalHeader/Navigation/DropDown/index.jsx
  front/src/Components/Header/OptionalHeader/Navigation/index.jsx
  front/src/Pages/CustomPage/ColorPage/index.jsx
  front/src/context/UserDataContext.jsx
Labels: 🔨 Refactor

#176 Be/feat/155 추가 질문 기능
  backend/recommend/src/main/java/com/poongcha/recommend/application/additionalquestion/AdditionalQuestionCommandService.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/additionalquestion/AdditionalQuestionMapper.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/additionalquestion/AdditionalQuestionQueryService.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/dto/AdditionalQuestionCreateRequest.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/dto/AdditionalQuestionOptionNameResponse.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/dto/AdditionalQuestionResponse.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/additionalquestion/AdditionalQuestion.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/additionalquestion/AdditionalQuestionOption.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/additionalquestion/AdditionalQuestionOptionName.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/additionalquestion/AdditionalQuestionRepository.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/additionalquestion/Description.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/additionalquestion/Topic.java
  backend/recommend/src/main/java/com/poongcha/recommend/exception/BadRequestException.java
  backend/recommend/src/main/java/com/poongcha/recommend/exception/NotFoundException.java
  backend/recommend/src/main/java/com/poongcha/recommend/presentation/AdditionalQuestionController.java
  backend/recommend/src/test/java/com/poongcha/recommend/acceptance/AdditionalQuestionAcceptanceTest.java
  backend/recommend/src/test/java/com/poongcha/recommend/acceptance/AdditionalQuestionSteps.java
  backend/recommend/src/test/java/com/poongcha/recommend/util/DataInitializeExecutionListener.java
  backend/recommend/src/test/java/com/poongcha/recommend/util/RecommendAcceptanceTest.java
Labels: ✨ Feature, 📃 Docs, 📬 API, ✅ Test

#174 FE/0821/상황별 이미지 표시, + 버튼 표시
  .gitignore
  front/src/Components/Common/TooltipProvider/index.jsx
  front/src/Components/Custom/OptionTagLabel/index.jsx
  front/src/Pages/CustomPage/OptionPage/OptionCatalogue/SituationView/OptionTooltip.jsx
  front/src/Pages/CustomPage/OptionPage/OptionCatalogue/SituationView/index.jsx
  front/src/Pages/CustomPage/OptionPage/OptionCatalogue/index.jsx
  front/src/Pages/CustomPage/OptionPage/OptionPopup/Card.jsx
  front/src/Pages/CustomPage/OptionPage/index.jsx
  front/src/Pages/CustomPage/OptionPage/tagData.js
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/index.jsx
Labels: ✨ Feature

#179 FE/0821/선택페이지 색상 api 연결
  front/.gitignore
  front/src/Components/Custom/CarView/CarRotateViewer/index.jsx
  front/src/Pages/CustomPage/ColorPage/index.jsx
  front/src/apis/custom.js
  front/src/apis/test.txt
  front/src/utils/fetch.js
Labels: 📬 API, 🔨 Refactor

#186 Be/feat/185 라이프스타일 상황 태그
  backend/recommend/src/main/java/com/poongcha/recommend/application/dto/LifestylePersonaSituationTagCreateRequest.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/lifestylePersonasituationTag/LifestylePersonaSituationTagCommandService.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/lifestylePersonasituationTag/LifestylePersonaSituationTagMapper.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/lifestylepersonasituationtag/LifestylePersonaSituationTag.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/lifestylepersonasituationtag/LifestylePersonaSituationTagRepository.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/lifestylepersonasituationtag/TagName.java
  backend/recommend/src/main/java/com/poongcha/recommend/presentation/LifestylePersonaSituationTagController.java
  backend/recommend/src/test/java/com/poongcha/recommend/acceptance/LifestyleSituationTagAcceptanceTest.java
  backend/recommend/src/test/java/com/poongcha/recommend/acceptance/LifestyleSituationTagSteps.java
Labels: ✨ Feature, 📃 Docs, 📬 API, ✅ Test

#187 BE/08.22/라이프스타일 상황 태그 기능 구현
  backend/recommend/src/main/java/com/poongcha/recommend/application/dto/LifestylePersonaSituationTagResponse.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/lifestylePersonasituationTag/LifestylePersonaSituationTagMapper.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/lifestylePersonasituationtag/LifestylePersonaSituationTagCommandService.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/lifestylePersonasituationtag/LifestylePersonaSituationTagMapper.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/lifestylePersonasituationtag/LifestylePersonaSituationTagQueryService.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/lifestylepersonasituationtag/LifestylePersonaSituationTagRepository.java
  backend/recommend/src/main/java/com/poongcha/recommend/presentation/LifestylePersonaSituationTagController.java
  backend/recommend/src/test/java/com/poongcha/recommend/acceptance/LifestyleSituationTagAcceptanceTest.java
  backend/recommend/src/test/java/com/poongcha/recommend/acceptance/LifestyleSituationTagSteps.java
  backend/recommend/src/test/java/com/poongcha/recommend/util/DataInitializeExecutionListener.java
Labels: ✨ Feature, 📃 Docs, 📬 API, ✅ Test

#188 Be/08.22/라이프스타일 퍼소나 기능 구현
  backend/recommend/src/main/java/com/poongcha/recommend/application/dto/LifestyleInterviewCreateRequest.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/dto/LifestyleInterviewResponse.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/dto/LifestylePersonaCreateRequest.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/dto/LifestylePersonaProfileResponse.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/dto/LifestylePersonaResponse.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/lifestylepersona/LifestylePersonaCommandService.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/lifestylepersona/LifestylePersonaMapper.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/lifestylepersona/LifestylePersonaQueryService.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/lifestylepersona/Answer.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/lifestylepersona/CoverImageUrl.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/lifestylepersona/LifestyleInterview.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/lifestylepersona/LifestylePersona.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/lifestylepersona/LifestylePersonaAdditionalQuestionOption.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/lifestylepersona/LifestylePersonaLifestylePersonaSituationTag.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/lifestylepersona/LifestylePersonaProfile.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/lifestylepersona/LifestylePersonaRepository.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/lifestylepersona/Question.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/lifestylepersona/RepresentativePhrase.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/lifestylepersonasituationtag/LifestylePersonaSituationTagRepository.java
  backend/recommend/src/main/java/com/poongcha/recommend/presentation/LifestylePersonaController.java
  backend/recommend/src/test/java/com/poongcha/recommend/acceptance/LifestylePersonaAcceptanceTest.java
  backend/recommend/src/test/java/com/poongcha/recommend/acceptance/LifestylePersonaSteps.java
  backend/recommend/src/test/java/com/poongcha/recommend/util/DataInitializeExecutionListener.java
Labels: ✨ Feature, 📃 Docs, 📬 API, ✅ Test

#189 Fe/0822/견적내기페이지 context적용
  front/src/Components/Common/Summary/SelectedItem/SelectedItem.jsx
  front/src/Components/Common/Summary/index.jsx
  front/src/Components/Custom/ColorOptionGroup/ColorOption.jsx
  front/src/Components/Header/OptionalHeader/Navigation/DropDown/index.jsx
  front/src/Pages/EndPage/index.jsx
  front/src/Pages/EtcPage/index.jsx
  front/src/Pages/ResultPage/index.jsx
  front/src/context/UserDataContext.jsx
Labels: ✨ Feature

#182 FE/0821/userData 헤더, 요금 상세 반영
  front/src/Components/Common/Summary/SelectedItem/SelectedItem.jsx
  front/src/Components/Common/Summary/index.jsx
  front/src/Components/Custom/TrimOptionLabel/index.jsx
  front/src/Components/Header/OptionalHeader/Navigation/DropDown/index.jsx
  front/src/Components/Header/OptionalHeader/Navigation/index.jsx
  front/src/Components/Result/Accordian/index.jsx
  front/src/Pages/CustomPage/ColorPage/index.jsx
  front/src/Pages/CustomPage/OptionPage/OptionCatalogue/DefaultView/index.jsx
  front/src/Pages/CustomPage/OptionPage/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/mockData.js
  front/src/Pages/EndPage/index.jsx
  front/src/Pages/EtcPage/index.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/index.jsx
  front/src/context/UserDataContext.jsx
Labels: ✨ Feature

#192 FE/0822/설문 api 연결
  front/src/Components/Common/RadioGroup/index.jsx
  front/src/Components/Survey/AgeQuestionLabel/index.jsx
  front/src/Components/Survey/ExtraQuestionLabel/index.jsx
  front/src/Pages/EtcPage/QNASummary/index.jsx
  front/src/Pages/SurveyPage/AgeSurvey/index.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/index.jsx
  front/src/Pages/SurveyPage/index.jsx
  front/src/Pages/SurveyPage/index.reducer.js
  front/src/apis/survey.js
  front/src/utils/constants.jsx
Labels: 📬 API

#193 Be/feat/190 추천 피드백 기능 구현
  backend/boot-loader/src/main/resources/application-prod.yml
  backend/car/src/main/resources/application-prod.yml
  backend/car/src/test/java/com/poongcha/car/acceptance/CarEstimateAcceptanceTest.java
  backend/car/src/test/java/com/poongcha/car/acceptance/CarEstimateSteps.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/dto/RecommendationFeedbackCreateRequest.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/dto/RecommendationFeedbackResponse.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/recommendationfeedback/RecommendationFeedbackCommandService.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/recommendationfeedback/RecommendationFeedbackMapper.java
  backend/recommend/src/main/java/com/poongcha/recommend/application/recommendationfeedback/RecommendationFeedbackQueryService.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/recommendationfeedback/FeedbackScore.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/recommendationfeedback/RecommendationFeedback.java
  backend/recommend/src/main/java/com/poongcha/recommend/domain/recommendationfeedback/RecommendationFeedbackRepository.java
  backend/recommend/src/main/java/com/poongcha/recommend/presentation/RecommendationFeedbackController.java
  backend/recommend/src/main/resources/application-prod.yml
  backend/recommend/src/test/java/com/poongcha/recommend/acceptance/RecommendationFeedbackAcceptanceTest.java
  backend/recommend/src/test/java/com/poongcha/recommend/acceptance/RecommendationFeedbackSteps.java
  backend/recommend/src/test/java/com/poongcha/recommend/util/DataInitializeExecutionListener.java
Labels: ✨ Feature, 📃 Docs, 📬 API, ✅ Test

#194 Fe/0822/테스트코드 작성 추천페이지
  front/babel.config.cjs
  front/jest.config.cjs
  front/jest.setup.js
  front/jsconfig.json
  front/package-lock.json
  front/package.json
  front/src/Components/Common/Button/Button.test.jsx
  front/src/Components/Common/RadioGroup/RadioGroup.test.jsx
  front/vite.config.js
Labels: ✨ Feature, ✅ Test

#196 Fe/0823/multi radio리팩토링
  front/src/Components/Common/RadioGroup/Label/index.jsx
  front/src/Components/Common/RadioGroup/index.jsx
  front/src/Components/Custom/ModelItemOptionLabel/index.jsx
  front/src/Components/Custom/OptionTagLabel/index.jsx
  front/src/Components/Custom/TrimOptionLabel/index.jsx
  front/src/Components/Survey/AgeQuestionLabel/index.jsx
  front/src/Components/Survey/ExtraQuestionLabel/index.jsx
  front/src/Components/Survey/LifestyleQuestionLabel/index.jsx
  front/src/Pages/CustomPage/OptionPage/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/mockData.js
  front/src/Pages/SurveyPage/LifestyleSurvey/index.jsx
Labels: 🔨 Refactor

#199 FE/0823/색상선택 데이터 변경
  front/src/Components/Custom/ColorOptionGroup/ColorOption.jsx
  front/src/Components/Custom/ColorOptionGroup/index.jsx
  front/src/Pages/CustomPage/ColorPage/ColorChangePopup/index.jsx
  front/src/Pages/CustomPage/ColorPage/ColorCustomSIdeBar/index.jsx
  front/src/Pages/CustomPage/ColorPage/index.jsx
  front/src/apis/custom.js
  front/src/utils/fetch.js
Labels: 🔨 Refactor

#197 FE/0823/트림 데이터 연결
  front/src/Components/Common/Summary/index.jsx
  front/src/Components/Custom/DefaultOptionPopup/index.jsx
  front/src/Components/Custom/TrimOptionLabel/DefaultOption.jsx
  front/src/Components/Custom/TrimOptionLabel/index.jsx
  front/src/Components/Header/OptionalHeader/Navigation/index.jsx
  front/src/Pages/CustomPage/OptionPage/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimChangePopup/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/index.jsx
  front/src/Pages/EtcPage/QNASummary/index.jsx
  front/src/Pages/ResultPage/Card/index.jsx
  front/src/Pages/ResultPage/ShareUrlPopup/index.jsx
  front/src/Pages/ResultPage/index.jsx
  front/src/Pages/SurveyPage/ExtraSurvey/index.jsx
  front/src/apis/custom.js
  front/src/context/UserDataContext.jsx
Labels: 📬 API

#201 Be/setting/200 배포 스크립트 및 워크플로우 수정
  .github/workflows/backend-cicd.yml
  deploy/scripts/restart-server.sh
Labels: 🌏 Deploy, 🐞 BugFix

#204 FE/0828/옵션 상황별 페이지 + 버튼 고정
  front/src/Pages/CustomPage/OptionPage/OptionCatalogue/SituationView/index.jsx
  front/src/Pages/CustomPage/OptionPage/optionData.js
  front/src/Pages/CustomPage/TrimPage/ModelItemsDescriptionPopup/index.jsx
  front/src/Pages/CustomPage/TrimPage/TrimCustomSideBar/index.jsx
  front/src/Pages/SurveyPage/AgeSurvey/index.jsx
Labels: 🔨 Refactor
